global using Moq;
global using FluentAssertions;
global using Infrastucture.Enums;
global using Infrastucture.Models;
global using Microsoft.Extensions.Logging;
global using Infrastucture.Services.Abstractions;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using StackExchange.Redis;